<?php
/**
 * @package pro
 */
?>

<div class="progression-studios-social-icons">
	
	<?php if (get_theme_mod( 'progression_studios_header_facebook')) : ?><a href="<?php echo esc_url(get_theme_mod('progression_studios_header_facebook')); ?>" target="_blank" class="progression-studios-facebook" title="<?php echo esc_html__( 'Facebook', 'habitat-progression' ); ?>"><i class="fa fa-facebook"></i></a><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_header_twitter')) : ?><a href="<?php echo esc_url(get_theme_mod('progression_studios_header_twitter')); ?>" target="_blank" class="progression-studios-twitter" title="<?php echo esc_html__( 'Twitter', 'habitat-progression' ); ?>"><i class="fa fa-twitter"></i></a><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_header_instagram')) : ?><a href="<?php echo esc_url(get_theme_mod('progression_studios_header_instagram')); ?>" target="_blank" class="progression-studios-instagram" title="<?php echo esc_html__( 'Instagram', 'habitat-progression' ); ?>"><i class="fa fa-instagram"></i></a><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_header_spotify')) : ?><a href="<?php echo esc_url(get_theme_mod('progression_studios_header_spotify')); ?>" target="_blank" class="progression-studios-spotify" title="<?php echo esc_html__( 'Spotify', 'habitat-progression' ); ?>"><i class="fa fa-spotify"></i></a><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_header_youtube' )) : ?><a href="<?php echo esc_url(get_theme_mod('progression_studios_header_youtube')); ?>" target="_blank" class="progression-studios-youtube" title="<?php echo esc_html__( 'Youtube', 'habitat-progression' ); ?>"><i class="fa fa-youtube-play"></i></a><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_header_vimeo')) : ?><a href="<?php echo esc_url(get_theme_mod('progression_studios_header_vimeo')); ?>" target="_blank" class="progression-studios-vimeo" title="<?php echo esc_html__( 'Vimeo', 'habitat-progression' ); ?>"><i class="fa fa-vimeo"></i></a><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_header_google_plus')) : ?><a href="<?php echo esc_url(get_theme_mod('progression_studios_header_google_plus')); ?>" target="_blank" class="progression-studios-google-plus" title="<?php echo esc_html__( 'Google+', 'habitat-progression' ); ?>"><i class="fa fa-google-plus"></i></a><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_header_pinterest')) : ?><a href="<?php echo esc_url(get_theme_mod('progression_studios_header_pinterest')); ?>" target="_blank" class="progression-studios-pinterest" title="<?php echo esc_html__( 'Pinterest', 'habitat-progression' ); ?>"><i class="fa fa-pinterest"></i></a><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_header_soundcloud')) : ?><a href="<?php echo esc_url(get_theme_mod('progression_studios_header_soundcloud')); ?>" target="_blank" class="progression-studios-soundcloud" title="<?php echo esc_html__( 'Soundcloud', 'habitat-progression' ); ?>"><i class="fa fa-soundcloud"></i></a><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_header_linkedin')) : ?><a href="<?php echo esc_url(get_theme_mod('progression_studios_header_linkedin')); ?>" target="_blank" class="progression-studios-linkedin" title="<?php echo esc_html__( 'LinkedIn', 'habitat-progression' ); ?>"><i class="fa fa-linkedin"></i></a><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_header_snapchat')) : ?><a href="<?php echo esc_url(get_theme_mod('progression_studios_header_snapchat')); ?>" target="_blank" class="progression-studios-snapchat" title="<?php echo esc_html__( 'Snapchat', 'habitat-progression' ); ?>"><i class="fa fa-snapchat-ghost"></i></a><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_header_tumblr')) : ?><a href="<?php echo esc_url(get_theme_mod('progression_studios_header_tumblr')); ?>" target="_blank" class="progression-studios-tumblr" title="<?php echo esc_html__( 'Tumblr', 'habitat-progression' ); ?>"><i class="fa fa-tumblr"></i></a><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_header_flickr')) : ?><a href="<?php echo esc_url(get_theme_mod('progression_studios_header_flickr')); ?>" target="_blank" class="progression-studios-flickr" title="<?php echo esc_html__( 'Flickr', 'habitat-progression' ); ?>"><i class="fa fa-flickr"></i></a><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_header_dribbble')) : ?><a href="<?php echo esc_url(get_theme_mod('progression_studios_header_dribbble')); ?>" target="_blank" class="progression-studios-dribbble" title="<?php echo esc_html__( 'Dribbble', 'habitat-progression' ); ?>"><i class="fa fa-dribbble"></i></a><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_header_vk')) : ?><a href="<?php echo esc_url(get_theme_mod('progression_studios_header_vk')); ?>" target="_blank" class="progression-studios-vk" title="<?php echo esc_html__( 'VK', 'habitat-progression' ); ?>"><i class="fa fa-vk"></i></a><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_header_wordpress')) : ?><a href="<?php echo esc_url(get_theme_mod('progression_studios_header_wordpress')); ?>" target="_blank" class="progression-studios-wordpress" title="<?php echo esc_html__( 'WordPress', 'habitat-progression' ); ?>"><i class="fa fa-wordpress"></i></a><?php endif; ?>
	
	<?php if (get_theme_mod( 'progression_studios_header_houzz')) : ?><a href="<?php echo esc_attr(get_theme_mod('progression_studios_header_houzz')); ?>" target="_blank" class="progression-studios-houzz" title="<?php echo esc_html__( 'Houzz', 'habitat-progression' ); ?>"><i class="fa fa-houzz"></i></a><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_header_behance')) : ?><a href="<?php echo esc_attr(get_theme_mod('progression_studios_header_behance')); ?>" target="_blank" class="progression-studios-behance" title="<?php echo esc_html__( 'Behance', 'habitat-progression' ); ?>"><i class="fa fa-behance"></i></a><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_header_github')) : ?><a href="<?php echo esc_attr(get_theme_mod('progression_studios_header_github')); ?>" target="_blank" class="progression-studios-github" title="<?php echo esc_html__( 'Github', 'habitat-progression' ); ?>"><i class="fa fa-github"></i></a><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_header_lastfm')) : ?><a href="<?php echo esc_attr(get_theme_mod('progression_studios_header_lastfm')); ?>" target="_blank" class="progression-studios-lastfm" title="<?php echo esc_html__( 'LastFM', 'habitat-progression' ); ?>"><i class="fa fa-lastfm"></i></a><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_header_medium')) : ?><a href="<?php echo esc_attr(get_theme_mod('progression_studios_header_medium')); ?>" target="_blank" class="progression-studios-medium" title="<?php echo esc_html__( 'Medium', 'habitat-progression' ); ?>"><i class="fa fa-medium"></i></a><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_header_tripadvisor')) : ?><a href="<?php echo esc_attr(get_theme_mod('progression_studios_header_tripadvisor')); ?>" target="_blank" class="progression-studios-tripadvisor" title="<?php echo esc_html__( 'Trip Advisor', 'habitat-progression' ); ?>"><i class="fa fa-tripadvisor"></i></a><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_header_twitch')) : ?><a href="<?php echo esc_attr(get_theme_mod('progression_studios_header_twitch')); ?>" target="_blank" class="progression-studios-twitch" title="<?php echo esc_html__( 'Twitch', 'habitat-progression' ); ?>"><i class="fa fa-twitch"></i></a><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_header_yelp')) : ?><a href="<?php echo esc_attr(get_theme_mod('progression_studios_header_yelp')); ?>" target="_blank" class="progression-studios-yelp" title="<?php echo esc_html__( 'Yelp', 'habitat-progression' ); ?>"><i class="fa fa-yelp"></i></a><?php endif; ?>
	
	<?php if (get_theme_mod( 'progression_studios_header_mail')) : ?><a href="mailto:<?php echo esc_attr(get_theme_mod('progression_studios_header_mail')); ?>" class="progression-studios-mail" title="<?php echo esc_html__( 'Email', 'habitat-progression' ); ?>"><i class="fa fa-envelope"></i></a><?php endif; ?>
	
	<div class="clearfix-pro"></div>
</div><!-- close .progression-studios-social-icons -->