<?php
/**
 * @package pro
 */
?>
<div class="progression-studios-social-icons">
	
	<?php if (get_theme_mod( 'progression_studios_footer_facebook')) : ?><a href="<?php echo esc_url(get_theme_mod('progression_studios_footer_facebook')); ?>" target="_blank" class="progression-studios-facebook" title="<?php echo esc_html__( 'Facebook', 'habitat-progression' ); ?>"><i class="fa fa-facebook"></i><span><?php echo esc_html__( 'Facebook', 'habitat-progression' ); ?></span></a><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_footer_twitter')) : ?><a href="<?php echo esc_url(get_theme_mod('progression_studios_footer_twitter')); ?>" target="_blank" class="progression-studios-twitter" title="<?php echo esc_html__( 'Twitter', 'habitat-progression' ); ?>"><i class="fa fa-twitter"></i><span><?php echo esc_html__( 'Twitter', 'habitat-progression' ); ?></span></a><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_footer_instagram')) : ?><a href="<?php echo esc_url(get_theme_mod('progression_studios_footer_instagram')); ?>" target="_blank" class="progression-studios-instagram" title="<?php echo esc_html__( 'Instagram', 'habitat-progression' ); ?>"><i class="fa fa-instagram"></i><span><?php echo esc_html__( 'Instagram', 'habitat-progression' ); ?></span></a><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_footer_spotify')) : ?><a href="<?php echo esc_url(get_theme_mod('progression_studios_footer_spotify')); ?>" target="_blank" class="progression-studios-spotify" title="<?php echo esc_html__( 'Spotify', 'habitat-progression' ); ?>"><i class="fa fa-spotify"></i><span><?php echo esc_html__( 'Spotify', 'habitat-progression' ); ?></span></a><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_footer_youtube' )) : ?><a href="<?php echo esc_url(get_theme_mod('progression_studios_footer_youtube')); ?>" target="_blank" class="progression-studios-youtube" title="<?php echo esc_html__( 'Youtube', 'habitat-progression' ); ?>"><i class="fa fa-youtube-play"></i><span><?php echo esc_html__( 'Youtube', 'habitat-progression' ); ?></span></a><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_footer_vimeo')) : ?><a href="<?php echo esc_url(get_theme_mod('progression_studios_footer_vimeo')); ?>" target="_blank" class="progression-studios-vimeo" title="<?php echo esc_html__( 'Vimeo', 'habitat-progression' ); ?>"><i class="fa fa-vimeo"></i><span><?php echo esc_html__( 'Vimeo', 'habitat-progression' ); ?></span></a><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_footer_google_plus')) : ?><a href="<?php echo esc_url(get_theme_mod('progression_studios_footer_google_plus')); ?>" target="_blank" class="progression-studios-google-plus" title="<?php echo esc_html__( 'Google+', 'habitat-progression' ); ?>"><i class="fa fa-google-plus"></i><span><?php echo esc_html__( 'Google+', 'habitat-progression' ); ?></span></a><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_footer_pinterest')) : ?><a href="<?php echo esc_url(get_theme_mod('progression_studios_footer_pinterest')); ?>" target="_blank" class="progression-studios-pinterest" title="<?php echo esc_html__( 'Pinterest', 'habitat-progression' ); ?>"><i class="fa fa-pinterest"></i><span><?php echo esc_html__( 'Pinterest', 'habitat-progression' ); ?></span></a><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_footer_soundcloud')) : ?><a href="<?php echo esc_url(get_theme_mod('progression_studios_footer_soundcloud')); ?>" target="_blank" class="progression-studios-soundcloud" title="<?php echo esc_html__( 'Soundcloud', 'habitat-progression' ); ?>"><i class="fa fa-soundcloud"></i><span><?php echo esc_html__( 'Soundcloud', 'habitat-progression' ); ?></span></a><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_footer_linkedin')) : ?><a href="<?php echo esc_url(get_theme_mod('progression_studios_footer_linkedin')); ?>" target="_blank" class="progression-studios-linkedin" title="<?php echo esc_html__( 'LinkedIn', 'habitat-progression' ); ?>"><i class="fa fa-linkedin"></i><span><?php echo esc_html__( 'LinkedIn', 'habitat-progression' ); ?></span></a><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_footer_snapchat')) : ?><a href="<?php echo esc_url(get_theme_mod('progression_studios_footer_snapchat')); ?>" target="_blank" class="progression-studios-snapchat" title="<?php echo esc_html__( 'Snapchat', 'habitat-progression' ); ?>"><i class="fa fa-snapchat-ghost"></i><span><?php echo esc_html__( 'Snapchat', 'habitat-progression' ); ?></span></a><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_footer_tumblr')) : ?><a href="<?php echo esc_url(get_theme_mod('progression_studios_footer_tumblr')); ?>" target="_blank" class="progression-studios-tumblr" title="<?php echo esc_html__( 'Tumblr', 'habitat-progression' ); ?>"><i class="fa fa-tumblr"></i><span><?php echo esc_html__( 'Tumblr', 'habitat-progression' ); ?></span></a><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_footer_flickr')) : ?><a href="<?php echo esc_url(get_theme_mod('progression_studios_footer_flickr')); ?>" target="_blank" class="progression-studios-flickr" title="<?php echo esc_html__( 'Flickr', 'habitat-progression' ); ?>"><i class="fa fa-flickr"></i><span><?php echo esc_html__( 'Flickr', 'habitat-progression' ); ?></span></a><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_footer_dribbble')) : ?><a href="<?php echo esc_url(get_theme_mod('progression_studios_footer_dribbble')); ?>" target="_blank" class="progression-studios-dribbble" title="<?php echo esc_html__( 'Dribbble', 'habitat-progression' ); ?>"><i class="fa fa-dribbble"></i><span><?php echo esc_html__( 'Dribbble', 'habitat-progression' ); ?></span></a><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_footer_vk')) : ?><a href="<?php echo esc_url(get_theme_mod('progression_studios_footer_vk')); ?>" target="_blank" class="progression-studios-vk" title="<?php echo esc_html__( 'VK', 'habitat-progression' ); ?>"><i class="fa fa-vk"></i><span><?php echo esc_html__( 'VK', 'habitat-progression' ); ?></span></a><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_footer_wordpress')) : ?><a href="<?php echo esc_url(get_theme_mod('progression_studios_footer_wordpress')); ?>" target="_blank" class="progression-studios-wordpress" title="<?php echo esc_html__( 'WordPress', 'habitat-progression' ); ?>"><i class="fa fa-wordpress"></i><span><?php echo esc_html__( 'WordPress', 'habitat-progression' ); ?></span></a><?php endif; ?>
	
	<?php if (get_theme_mod( 'progression_studios_footer_houzz')) : ?><a href="<?php echo esc_attr(get_theme_mod('progression_studios_footer_houzz')); ?>" target="_blank" class="progression-studios-houzz" title="<?php echo esc_html__( 'Houzz', 'habitat-progression' ); ?>"><i class="fa fa-houzz"></i><span><?php echo esc_html__( 'Houzz', 'habitat-progression' ); ?></span></a><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_footer_behance')) : ?><a href="<?php echo esc_attr(get_theme_mod('progression_studios_footer_behance')); ?>" target="_blank" class="progression-studios-behance" title="<?php echo esc_html__( 'Behance', 'habitat-progression' ); ?>"><i class="fa fa-behance"></i><span><?php echo esc_html__( 'Behance', 'habitat-progression' ); ?></span></a><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_footer_github')) : ?><a href="<?php echo esc_attr(get_theme_mod('progression_studios_footer_github')); ?>" target="_blank" class="progression-studios-github" title="<?php echo esc_html__( 'GitHub', 'habitat-progression' ); ?>"><i class="fa fa-github"></i><span><?php echo esc_html__( 'Github', 'habitat-progression' ); ?></span></a><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_footer_lastfm')) : ?><a href="<?php echo esc_attr(get_theme_mod('progression_studios_footer_lastfm')); ?>" target="_blank" class="progression-studios-lastfm" title="<?php echo esc_html__( 'LastFM', 'habitat-progression' ); ?>"><i class="fa fa-lastfm"></i><span><?php echo esc_html__( 'LastFM', 'habitat-progression' ); ?></span></a><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_footer_medium')) : ?><a href="<?php echo esc_attr(get_theme_mod('progression_studios_footer_medium')); ?>" target="_blank" class="progression-studios-medium" title="<?php echo esc_html__( 'Medium', 'habitat-progression' ); ?>"><i class="fa fa-medium"></i><span><?php echo esc_html__( 'Medium', 'habitat-progression' ); ?></span></a><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_footer_tripadvisor')) : ?><a href="<?php echo esc_attr(get_theme_mod('progression_studios_footer_tripadvisor')); ?>" target="_blank" class="progression-studios-tripadvisor" title="<?php echo esc_html__( 'Trip Advisor', 'habitat-progression' ); ?>"><i class="fa fa-tripadvisor"></i><span><?php echo esc_html__( 'Trip Advisor', 'habitat-progression' ); ?></span></a><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_footer_twitch')) : ?><a href="<?php echo esc_attr(get_theme_mod('progression_studios_footer_twitch')); ?>" target="_blank" class="progression-studios-twitch" title="<?php echo esc_html__( 'Twitch', 'habitat-progression' ); ?>"><i class="fa fa-twitch"></i><span><?php echo esc_html__( 'Twitch', 'habitat-progression' ); ?></span></a><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_footer_yelp')) : ?><a href="<?php echo esc_attr(get_theme_mod('progression_studios_footer_yelp')); ?>" target="_blank" class="progression-studios-yelp" title="<?php echo esc_html__( 'Yelp', 'habitat-progression' ); ?>"><i class="fa fa-yelp"></i><span><?php echo esc_html__( 'Yelp', 'habitat-progression' ); ?></span></a><?php endif; ?>
	
	<?php if (get_theme_mod( 'progression_studios_footer_mail')) : ?><a href="mailto:<?php echo esc_attr(get_theme_mod('progression_studios_footer_mail')); ?>" class="progression-studios-mail" title="<?php echo esc_html__( 'Email', 'habitat-progression' ); ?>"><i class="fa fa-envelope"></i><span><?php echo esc_html__( 'Email', 'habitat-progression' ); ?></span></a><?php endif; ?>
	
	<div class="clearfix-pro"></div>
</div><!-- close .progression-studios-social-icons -->